include: package:lints/recommended.yaml

analyzer:
  exclude: [.dart_tool/**]

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables