name: mate
description: A lightweight math library for dart
version: 0.0.1
homepage: https://github.com/theiskaa/mate
issue_tracker: https://github.com/theiskaa/mate/issues
documentation: https://github.com/theiskaa/mate#readme

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: