name: mate
description: A simple and lightweight math library, that can parse and calculate string expressions.
version: 0.0.2
homepage: https://github.com/theiskaa/mate
issue_tracker: https://github.com/theiskaa/mate/issues
documentation: https://github.com/theiskaa/mate#readme

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.19.2
  lints: ^1.0.1